# Generated by Django 5.1.3 on 2024-11-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_comment_message_comment_message_not_empty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='message_not_empty',
        ),
    ]
