# Generated by Django 5.1.3 on 2024-11-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_comment_message_not_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
